import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Kanit } from "next/font/google";

import NavMobile from "./components/NavMobile";
import Navbar from "./components/Navbar";
const kanit = Kanit({
  subsets: ["thai"],
  weight: "400"
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        {children}
        <NavMobile/>
        </body>
    </html>
  );
}
